### ISSUE TITLE
lex_node colcon build fails asking for AudioData.h

### ISSUE THREAD

**Issue by wezzoid** [aws-robotics/lex-ros1#2] opened 2018-12-06 10:15 UTC
Hi, I'm on Raspbian Stretch, ROS Kinetic. Following the lex-ros1 readme, I get this error during colcon build:

```Starting >>> lex_node
--- stderr: lex_node                               
In file included from /home/pi/colcon_ws/install/lex_common_msgs/include/lex_common_msgs/AudioTextConversation.h:11:0,
                 from /home/pi/colcon_ws/src/lex-ros1/lex_node/include/lex_node/lex_node.h:19,
                 from /home/pi/colcon_ws/src/lex-ros1/lex_node/src/lex_node.cpp:29:
/home/pi/colcon_ws/install/lex_common_msgs/include/lex_common_msgs/AudioTextConversationRequest.h:18:41: fatal error: audio_common_msgs/AudioData.h: No such file or directory
 #include <audio_common_msgs/AudioData.h>
                                         ^
compilation terminated.
make[2]: *** [CMakeFiles/lex_node_lib.dir/src/lex_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/lex_node_lib.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< lex_node	[ Exited with code 2 ]

Summary: 0 packages finished [16.1s]
  1 package failed: lex_node
  1 package had stderr output: lex_node
```

I'm using a separate colcon workspace for this.
I git cloned audio_common into my catkin ws, built and sourced it, and tried the colcon build again. Same error. I looked at the audio_common files and I don't see an AudioData.h.
I'm sure I'm doing something silly. I am a novice. Am I using the wrong audio package?

**Comment by xabxx** [comment] 2018-12-07 05:12
@wezzoid hi there!
I tried to follow your steps but couldn't reproduce this error, but it may be that I didn't understand you correctly.

If you have ros on your system, you would need to make sure that ros lib path is set by doing `source /opt/ros/ros-version(e.g. kinetic)/setup.bash`,
then, if you follow our readme instruction, you would notice that doing `rosdep install --from-paths src --ignore-src -r -y` will help you install lex_node's dependencies, and that includes audio_common_msgs, and you don't need to manually clone that ros package and source it.

The reason you couldn't see `audio_common_msgs/AudioData.h` in src code is because when a .msg file get built, it will get translated into source code by ROS client lib. please see section 3 [here](http://wiki.ros.org/msg) for more information about this. Thus, `audio_common_msgs/AudioData.h` will show up in the build folder but not in the source code. 

If you think I didn't understand you, could you provide me with steps to reproduce this error?

thanks!

**Comment by xabxx** [comment] 2018-12-13 18:13
@wezzoid Hi there. I am going to close this issue. Please feel free to open it if you are still running into this issue. Thanks!

**Closed by xabxx** 2018-12-13 18:13 UTC
Labels: question

**Comment by java-Xs** [comment] 2020-03-15 02:59
hi @xabxx ,How do you fix it? I have the same error.Thanks

**Comment by java-Xs** [comment] 2020-03-15 05:54
i fix this error. If you dont download audio_common, you shoud download this folder.first,the path of install, the header audio_common_msgs/AudioData.h must be exist, in the lex_node package,find a file CMakeList.txt, open it, add audio_common_msgs in find_package and catkin_package. So you can back the path/ros_ws ,retry this command:colcon build.
